searchlogger/form/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import welcome, prequestionnaire, preinstructions, pretask, precomparison,\
    strategy, task, question, postcomparison, thanks


urlpatterns = [
    url(r'^$', welcome),
    url(r'^welcome/', welcome, name='welcome'),
    url(r'^prequestionnaire/', prequestionnaire, name='prequestionnaire'),
    url(r'^pretask/', pretask, name='pretask'),
    url(r'^preinstructions/', preinstructions, name='preinstructions'),
    url(r'^precomparison/', precomparison, name='precomparison'),
    url(r'^strategy/(?P<question_index>[0-9]+)/$', strategy, name='strategy'),
    url(r'^task/(?P<question_index>[0-9]+)/$', task, name='task'),
    url(r'^question/(?P<question_index>[0-9]+)/$', question, name='question'),
    url(r'^postcomparison/', postcomparison, name='postcomparison'),
    url(r'^thanks/', thanks, name='thanks'),
]

searchlogger/searchlogger/urls.py
from django.conf.urls import url, include

from searchlogger.api import LocationEventResource


location_event_resource = LocationEventResource()

urlpatterns = [
    url(r'^api/', include(location_event_resource.urls)),
]

searchlogger/form/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

from .concerns import CONCERNS


def verbatim_choices(list_):
    return zip(list_, list_)


def choice_range(min_, max_):
    return verbatim_choices(range(min_, max_))


class Prequestionnaire(models.Model):
    user = models.ForeignKey(User)
    programming_years = models.CharField(
        verbose_name="How many years of experience do you have programming?",
        choices=verbatim_choices([
            "Less than one year", "1-2 years", "3-5 years",
            "6-9 years", "10-19 years", "20 more more years"
        ]),
        max_length=100,
        blank=True,
        null=True,
    )
    python_years = models.CharField(
        verbose_name=(
            "How many years of experience do you have programming " +
            "with Python or Python packages?"),
        choices=verbatim_choices([
            "Less than one year", "1-2 years", "3-5 years",
            "6-9 years", "10-19 years", "20 more more years"
        ]),
        max_length=100,
        blank=True,
        null=True,
    )
    professional_years = models.CharField(
        verbose_name="How many years of experience do you have programming professionally?",
        choices=verbatim_choices([
            "Less than one year", "1-2 years", "3-5 years",
            "6-9 years", "10-19 years", "20 more more years"
        ]),
        max_length=100,
        blank=True,
        null=True,
    )
    coding_reason = models.CharField(
        verbose_name="The main reason I write code is for:...",
        choices=verbatim_choices(["Work", "Research", "Hobbies", "Coursework"]),
        max_length=100,
        blank=True,
        null=True,
    )
    programming_profiency = models.CharField(
        verbose_name="How would you describe your proficiency as a programmer?",
        choices=verbatim_choices(["Novice", "Proficient", "Expert"]),
        max_length=100,
        blank=True,
        null=True,
    )
    python_proficiency = models.CharField(
        verbose_name="How would you describe your proficiency with Python?",
        choices=verbatim_choices(["Novice", "Proficient", "Expert"]),
        max_length=100,
        blank=True,
        null=True,
    )
    occupation = models.CharField(
        verbose_name="What is your primary occupation?",
        choices=verbatim_choices([
            "Software developer",
            "Systems administrator",
            "Project manager",
            "Quality assurance",
            "Graduate student",
            "Undergraduate student",
            "Other",
        ]),
        max_length=200,
        blank=True,
        null=True,
    )
    occupation_other = models.CharField(
        verbose_name="If 'Other', what is your occupation?",
        max_length=200,
        blank=True,
        null=True,
    )
    gender = models.CharField(
        verbose_name="What is your gender?",
        max_length=500,
        blank=True,
        null=True
    )


class Strategy(models.Model):
    user = models.ForeignKey(User)
    question_index = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    concern = models.CharField(
        verbose_name="Task: Find which package better satisfies this concern",
        max_length=1000,
    )
    strategy = models.CharField(
        verbose_name=(
            "What strategy will you use to find out which package " +
            "is better for this concern?"),
        help_text="Share 1-2 sentences.  This shouldn't take you more than 2 minutes.",
        max_length=10000
    )


class NotApplicableField(models.BooleanField):

    def __init__(self, *args, **kwargs):
        kwargs['verbose_name'] = "Don't know"
        kwargs['default'] = False
        super(self.__class__, self).__init__(*args, **kwargs)


class Question(models.Model):
    user = models.ForeignKey(User)
    question_index = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    concern = models.CharField(
        verbose_name="For this concern, which package is better?",
        max_length=1000
    )
    likert_comparison_evidence = models.IntegerField(
        verbose_name=(
            "Based on the evidence you have seen, which package " +
            "is better for this concern?"
        ),
        choices=choice_range(0, 5),
        null=True,
        blank=True,
    )
    na_likert_comparison_evidence = NotApplicableField()
    evidence = models.CharField(
        verbose_name="What evidence informs your rating?",
        help_text=(
            "Share 1-2 sentences with links if possible.  " +
            "This shouldn't take you more than 2 minutes."
        ),
        max_length=10000,
        null=True,
        blank=True
    )
    likert_confidence = models.IntegerField(
        verbose_name="How confident are you in your assessment of which is better?",
        choices=choice_range(0, 5),
        null=True,
        blank=True,
    )
    na_likert_confidence = NotApplicableField()
    # Deprecated fields (maintained so we don't delete data from database)
    likert_comparison = models.IntegerField(
        verbose_name="For this concern, which package is better?",
        choices=choice_range(0, 5),
        default=-1  # this is to avoid showing bogus option
    )
    likert_comparison_intuition = models.IntegerField(
        verbose_name=(
            "Based on your instinct, which package is better for this concern?"),
        choices=choice_range(0, 5),
        default=-1  # this is to avoid showing bogus option
    )
    likert_coverage = models.IntegerField(
        verbose_name="I found all the information that's relevant to this question.",
        choices=choice_range(0, 5),
        default=-1
    )
    scratch_work = models.CharField(
        verbose_name="Scratch work",
        max_length=10000,
        null=True,
        blank=True,
    )
    strategy = models.CharField(
        verbose_name="What was your strategy for answering this question?",
        help_text="What documents did you look at and why?",
        max_length=4000,
        null=True,
        blank=True
    )
    url1 = models.CharField(
        verbose_name="URL of indicator 1",
        max_length=1000,
        null=True,
        blank=True
    )
    url1_where = models.CharField(
        verbose_name="What web site does this URL point to?",
        max_length=1000,
        null=True,
        blank=True
    )
    url1_what = models.CharField(
        verbose_name="What information on that site helped you?",
        max_length=10000,
        null=True,
        blank=True
    )
    url1_why = models.CharField(
        verbose_name="Why was this helpful?",
        max_length=10000,
        null=True,
        blank=True
    )
    url2 = models.CharField(
        verbose_name="URL of indicator 2",
        max_length=1000,
        null=True,
        blank=True,
    )
    url2_where = models.CharField(
        verbose_name="What web site does this URL point to?",
        max_length=1000,
        null=True,
        blank=True,
    )
    url2_what = models.CharField(
        verbose_name="What information on that site helped you?",
        max_length=10000,
        null=True,
        blank=True,
    )
    url2_why = models.CharField(
        verbose_name="Why was this helpful?",
        max_length=10000,
        null=True,
        blank=True,
    )
    extra_information = models.CharField(
        verbose_name=(
            "What additional information do you want " +
            "to see to better answer this question?"),
        max_length=10000,
        null=True,
        blank=True,
    )
    comments = models.CharField(
        max_length=10000,
        null=True,
        blank=True,
    )


class QuestionEvent(models.Model):
    user = models.ForeignKey(User)
    question_index = models.IntegerField(db_index=True)
    time = models.DateTimeField(auto_now_add=True)
    event_type = models.CharField(max_length=300)


class PackageComparison(models.Model):
    user = models.ForeignKey(User)
    stage = models.CharField(
        choices=verbatim_choices(["before", "after"]),
        max_length=100
    )
    likert_quality_community = models.IntegerField(
        verbose_name="Which package has a better community for clients of the package?",
        choices=choice_range(0, 5),
        null=True,
        blank=True,
    )
    na_likert_quality_community = NotApplicableField()
    likert_quality_documentation = models.IntegerField(
        verbose_name="Which package has better documentation?",
        choices=choice_range(0, 5),
        null=True,
        blank=True,
    )
    na_likert_quality_documentation = NotApplicableField()
    likert_preference = models.IntegerField(
        verbose_name="Which package would you rather use?",
        choices=choice_range(0, 5),
        null=True,
        blank=True,
    )
    na_likert_preference = NotApplicableField()
    # Deprecated fields (maintained so we don't delete data from database)
    likert_community = models.IntegerField(
        verbose_name="Which package has a better community?",
        choices=choice_range(0, 5),
        default=-1,
    )
    likert_documentation = models.IntegerField(
        verbose_name="Which package has better documentation?",
        choices=choice_range(0, 5),
        default=-1,
    )


class ConcernRankField(models.CharField):

    def __init__(self, *args, **kwargs):
        kwargs['choices'] = verbatim_choices([concern['statement'] for concern in CONCERNS])
        kwargs['max_length'] = 1000
        kwargs['blank'] = True
        kwargs['null'] = True
        super(self.__class__, self).__init__(*args, **kwargs)


class Postquestionnaire(models.Model):
    user = models.ForeignKey(User)
    concern_rank1 = ConcernRankField(

searchlogger/form/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import logging
from django import forms
from django.forms import modelform_factory, Textarea, RadioSelect
from django.utils.safestring import mark_safe

from .models import Strategy, Question, Prequestionnaire, PackagePair,\
    PackageComparison, Postquestionnaire


logging.basicConfig(level=logging.INFO, format="%(message)s")


# Adapted from code at
# http://stackoverflow.com/questions/1134085/rendering-a-value-as-text-instead-of-field-inside-a-django-form
# This makes it possible to define additional markup as part
# of the model, which is totally bad practice, but makes it
# a lot more adaptable to generate HTML
# Assumption: the value to be shown does not include double-quotation marks.
class PlainTextWidget(forms.Widget):

    def __init__(self, tag, _class=None, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        self.tag = tag
        self._class = _class

    def render(self, _name, value, attrs):
        result = '<' + self.tag
        if self._class is not None:
            result += (' class=' + self._class)
        result += '>'
        result += mark_safe(value) if not None else '-'
        result += ('</' + self.tag + '>')
        result += "<input type=hidden name='" + _name + "' value=\"" + value + "\"/>"
        return result


StrategyForm = modelform_factory(
    Strategy,
    fields=[
        'strategy',
    ],
    widgets={
        'strategy': Textarea(),
    }
)


QuestionForm = modelform_factory(
    Question,
    fields=[
        'concern',
        'likert_comparison_evidence',
        'na_likert_comparison_evidence',
        'evidence',
        'likert_confidence',
        'na_likert_confidence',
    ],
    widgets={
        'concern': PlainTextWidget('p', 'question'),
        'likert_comparison_evidence': RadioSelect(),
        'evidence': Textarea(),
        'likert_confidence': RadioSelect(),
    }
)


PrequestionnaireForm = modelform_factory(
    Prequestionnaire,
    exclude=['user'],
)


PackageComparisonForm = modelform_factory(
    PackageComparison,
    fields=[
        'likert_quality_community',
        'na_likert_quality_community',
        'likert_quality_documentation',
        'na_likert_quality_documentation',
        'likert_preference',
        'na_likert_preference',
    ],
    widgets={
        'likert_quality_community': RadioSelect(),
        'likert_quality_documentation': RadioSelect(),
        'likert_preference': RadioSelect(),
    }
)


PostquestionnaireForm = modelform_factory(
    Postquestionnaire,
    fields=[
        'likert_perception_change',
        'na_likert_perception_change',
        'concern_rank1',
        'concern_rank2',
        'concern_rank3',
        'concern_rank4',
        'concern_rank5',
        'concern_rank6',
    ],
    widgets={
        'likert_perception_change': RadioSelect(),
    }
)


PackagePairForm = modelform_factory(
    PackagePair,
    exclude=['user']
)

searchlogger/form/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8" />
    <link rel='stylesheet' href="{% static "main/style/base.css" %}" />
<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
<script>
function addHeaderBefore(selector, text) {
  $(selector).before("<h2>" + text + "</h2>");
}

function markLikert(selector, start, end) {
  $(selector).prepend(
    "<li><p class='likert_range'>" + start + "</p></li>"
  ).append(
    "<li><p class='likert_range'>" + end + "</p></li>"
  );
}
</script>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        <form action="{% url 'logout' %}" method=GET>
            <input type=submit name=logout value="Log out" />
        </form>
        <hr/>
        {% block content %}
        {% endblock content %}
    </body>
</html>

searchlogger/form/templates/postcomparison.html
{% extends "base.html" %}
{% block head %}
<title>Comparison</title>
<script>
$(function() {

  markLikert('ul#id_likert_quality_community', "{{ package1 }}", "{{ package2 }}");
  markLikert('ul#id_likert_quality_documentation', "{{ package1 }}", "{{ package2 }}");
  markLikert('ul#id_likert_preference', "{{ package1 }}", "{{ package2 }}");
  markLikert('ul#id_likert_perception_change', "Disagree", "Agree");

  // Randomize the order of options in all drop-downs for ranking concerns.
  $(function() {

    $('select[name^=concern_rank]').each(function(_, select) {

      // Fisher-Yates shuffle of options
      // Note that we only perform the shuffle on all non-null options.
      // No matter how the shuffle is performed, the "------" options should still
      // appear at the top of the list of options.
      // Note that with this shuffling, it looks like the original selection is
      // still preserved even after we re-attach the elements.
      var options = $(select).children('option:not([value=""])');
      var swap_index;
      var random_index;
      var temp_option;
      for (swap_index = options.length - 1; swap_index > 0; swap_index--) {
        random_index = Math.floor(Math.random() * (swap_index + 1));
        temp_option = options[swap_index];
        options[swap_index] = options[random_index];
        options[random_index] = temp_option;
      }

      // Reattach options to the select element in random order.
      // Thanks for the tip on the right API calls to do this from:
      // http://trentrichardson.com/2013/12/16/sort-dom-elements-jquery/
      options.detach().appendTo(select);

    });

  });

});
</script>
{% endblock %}
{% block content %}
<h2>Compare the packages</h2>
<p>Now that you have spent some time answering these specific questions, please revisit the comparisons from earlier.</p>
<form action="{% url 'postcomparison' %}" method="post">
    {% csrf_token %}
    {{ comparison_form }}
    {{ feedback_form }}
    <div>
        <input type="submit" name="previous" value="Previous" />
        <input type="submit" name="next" value="Next" />
    </div>
</form>
{% endblock content %}

searchlogger/form/templates/precomparison.html
{% extends "base.html" %}
{% block head %}
<title>Comparison</title>
<script>
$(function() {
  markLikert('ul#id_likert_quality_community', "{{ package1 }}", "{{ package2 }}");
  markLikert('ul#id_likert_quality_documentation', "{{ package1 }}", "{{ package2 }}");
  markLikert('ul#id_likert_preference', "{{ package1 }}", "{{ package2 }}");
});
</script>
{% endblock %}
{% block content %}
<h2>Compare the Packages</h2>
<form action="{% url 'precomparison' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <div>
        <input type="submit" name="previous" value="Previous" />
        <input type="submit" name="next" value="Next" />
    </div>
</form>
{% endblock content %}

searchlogger/form/templates/preinstructions.html
{% extends "base.html" %}

{% block head %}
<title>Introductory Task</title>
{% endblock %}

{% block content %}
<form action="{% url 'preinstructions' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <h2>Instructions</h2>
    <p>
    Pretend you have just found out about these two packages, and
    are choosing which one to use.
    <br><br>
    Now, use the web to answer these two questions:
    <span class='li'>Which package has a <b>better community</b> for clients of the package?</span>
    <span class='li'>Which package has <b>better documentation</b>?</span>
    <br>
    You will have a few minutes for each package.
    The researcher will give you a countdown timer for each one.
    Tell the researcher when you are ready to continue, and the press <b>Next</b>.
    </p>
    <div>
        <input type="submit" name="previous" value="Previous" />
        <input type="submit" name="next" value="Next" />
    </div>
</form>
{% endblock %}

searchlogger/form/templates/prequestionnaire.html
{% extends "base.html" %}
{% block head %}
<title>Prequestionnaire</title>
{% endblock %}
{% block content %}
<h2>Prequestionnaire</h2>
<form action="{% url 'prequestionnaire' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <div>
        <input type="submit" name="previous" value="Previous" />
        <input type="submit" name="next" value="Next" />
    </div>
</form>
{% endblock %}

searchlogger/form/templates/pretask.html
{% extends "base.html" %}

{% block head %}
<title>Introductory Task</title>
{% endblock %}

{% block content %}
<form action="{% url 'pretask' %}" method="post">
    {% csrf_token %}
    <h2>Go!</h2>
    <p>
    <i>Reminder:</i> Use the web to answer these two questions:
    <span class='li'>Which package has a <b>better community</b> for clients of the package?</span>
    <span class='li'>Which package has <b>better documentation</b>?</span>
    <br/>
    The two packages you are comparing are {{ package1 }} and {{ package2 }}.
    Start with {{ package1 }}, and the researcher will let you know when to move on to {{ package2 }}.
    </p>
    <p>
    If you feel you have found all the information you want to find for a package, let the researcher know and you can move on.
    </p>
    <div>
        <input type="submit" name="previous" value="Previous" />
        <input type="submit" name="next" value="I'm done with this task" />
    </div>
</form>
{% endblock %}

searchlogger/form/templates/question.html
{% extends "base.html" %}
{% block head %}
<title>Answer - Question {{ question_index }}</title>
<script>
$(function() {
  markLikert('ul#id_likert_comparison_evidence', "{{ package1 }}", "{{ package2 }}");
  // markLikert('ul#id_likert_comparison_intuition', "{{ package1 }}", "{{ package2 }}");
  markLikert('ul#id_likert_confidence', "Not confident", "Confident");
});
</script>
{% endblock %}
{% block content %}
<form action="{% url 'question' question_index %}" method="post">
    {% csrf_token %}
    {{ form }}
    <br/><br/><br/><br/><br/>
    <p>
    Continue to the next page when you are done answering the questions on this page.
    </p>
    <div>
        <input type="submit" name="previous" value="Previous" />
        <input type="submit" name="next" value="Next" />
    </div>
</form>
{% endblock %}

searchlogger/form/templates/strategy.html
{% extends "base.html" %}
{% block head %}
<title>Strategy - Question {{ question_index }}</title>
<script>
$(function() {
});
</script>
{% endblock %}
{% block content %}
<form action="{% url 'strategy' question_index %}" method="post">
    {% csrf_token %}
    <p>
    In the next task, you will use the web to answer this question:<br>
    <b>{{ concern|capfirst }}</b>
    </p>
    {{ form }}
    <br/><br/><br/><br/><br/>
    <p>
    Tell the researcher when you are ready to continue.
    Once they have started the timer, press <b>Next</b>.
    </p>
    <div>
        <input type="submit" name="previous" value="Previous" />
        <input type="submit" name="next" value="Next" />
    </div>
</form>
{% endblock %}

searchlogger/form/templates/task.html
{% extends "base.html" %}
{% block head %}
<title>Start task - Question {{ question_index }}</title>
{% endblock %}
{% block content %}
<form action="{% url 'task' question_index %}" method="post">
    {% csrf_token %}
    <h2>Task</h2>
    <p>
    Use the web to answer this question:<br>
    <b>{{ concern|capfirst }}</b>
    <br/>
    </p>
    <p>
    The researcher will let you know when your time is up.
    If you have found all the information you want to find before the time is up, you may click <b>I'm done with this task</b>.
    </p>
    <div>
        <input type="submit" name="previous" value="Previous" />
        <input type="submit" name="next" value="I'm done with this task" />
    </div>
</form>
{% endblock %}

searchlogger/form/templates/thanks.html
{% extends "base.html" %}

{% block head %}
<title>Thank you!</title>
{% endblock %}

{% block content %}
<h2>Thank you for participating!</h2>
{% endblock %}

searchlogger/form/templates/welcome.html
{% extends "base.html" %}

{% block head %}
<title>Welcome</title>
{% endblock %}

{% block content %}
<h2>Welcome to the study!</h2>
<form action="{% url 'welcome' %}" method="post">
    <p>
    In this study, we ask you to compare the quality of support and documentation for packages.
    We give you two packages to compare, related to some task you might use code to do.
    We ask you to assess support and documentation by anticipating which package will better suit your needs if you were to use it for the programming project we give you.
    <br><br>
    For each task that we give you, we ask you to do the following:
    <span class='li'>Plan how you will learn about support and documentation</span>
    <span class='li'>Use the web to learn about support and documentation</span>
    <span class='li'>Answer questions about what you learned</span>
    <br>
    The second step will be timed.
    </p>
    <p>
    When you are ready to proceed, please press the "Next" button.
    </p>
    {% csrf_token %}
    {{ form }}
    <div>
        <input type="submit" name="next" value="Next" />
    </div>
</form>
{% endblock %}